os:
  - linux
language: java
dist: xenial
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.cache
    - $HOME/.m2

install: true

jobs:
  include:
    # Do the actual build (and test reporting)
    - stage: package (maven)
      script: mvn -B clean package

    - stage: report tests (sonarqube)
      if: branch =~ ^release\/.*$
      script: >-
        mvn -B -DskipTests=true org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar

    - stage: distribute
      if: branch =~ ^release\/.*$
      script: mvn -B -DskipTests=true deploy --settings ./ci/.travis-settings.xml
